### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by henryhardy** [theHazzard/spotify-remote#1]
On trying to pause a song.

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.1
**Thrown From**: [spotify-remote](https://github.com/theHazzard/spotify-remote) package, v0.5.2
### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At /Users/henryhardy/.atom/packages/spotify-remote/lib/spotify-remote.coffee:73

TypeError: Cannot read property '1' of null
    at /Users/henryhardy/.atom/packages/spotify-remote/lib/spotify-remote.coffee:73:80
    at ChildProcess.exithandler (child_process.js:222:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```
### Commands

```
     -2:38 core:select-all (atom-text-editor.editor.is-focused)
     -2:33.1.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
  2x -2:28.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:26.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:19.9.0 editor:toggle-soft-wrap (atom-text-editor.editor.is-focused)
     -2:15.5.0 core:select-all (atom-text-editor.editor.is-focused)
     -2:13.5.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -2:03.9.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -2:03.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:02.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:57.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:57.1.0 core:save (atom-text-editor.editor.is-focused)
  3x -1:56.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:54.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:53.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.8.0 spotify-remote:toggle (div.package-detail.panels-item)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.19
seti-icons, v0.4.5
spotify-remote, v0.5.2

# Dev
No dev packages
```

**Comment by pbnj** [comment]
+1

**Comment by theHazzard** [comment]
You must be playing a song before you can start using this plugin, otherwise spotify does not activate the mechanism of communication in order to send commands to it, I can show a notification with this info so I can avoid the horrible error notification that you need to close it manually.

**Comment by wayneseymour** [comment]
:+1:
